# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 08:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20170620_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 948381), editable=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 948381), editable=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Desigtn',
            field=models.CharField(db_column='Designation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Gmail',
            field=models.EmailField(db_column='GmailId', default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='IsTeanLead',
            field=models.BooleanField(db_column='IsTeanLead', default=0),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 932755), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 932755), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 932755), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 32, 48, 932755), editable=False),
        ),
    ]
