# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20170620_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='Billablestat',
            field=models.IntegerField(db_column='BillableStatus', default=None, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Employeestat',
            field=models.IntegerField(db_column='MemberStatus', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 414164), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 414164), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(db_column='Billablestatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 429763), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 429763), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Employeestatus',
            field=models.ForeignKey(db_column='Employeestatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Employee_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Technologies',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 414164), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 20, 40, 414164), editable=False),
        ),
    ]
