# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 09:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0071_auto_20170620_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 730371), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 730371), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Billablestat',
            field=models.IntegerField(db_column='Billablestat', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(db_column='BillableStatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 756440), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 756440), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Employeestat',
            field=models.IntegerField(db_column='Employeestat', default=None, null=True),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Employeestatus',
            field=models.ForeignKey(db_column='MemberStatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Employee_Status'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 732376), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 23, 17, 732376), editable=False),
        ),
    ]
