# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 09:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0072_auto_20170621_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 657951), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 657951), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 673574), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 673574), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Designation',
            field=models.ForeignKey(db_column='Designation', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Designations'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 673574), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 15, 7, 14, 673574), editable=False),
        ),
    ]
