# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 13:00
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20170626_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accessories',
            old_name='ID',
            new_name='Accessories',
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Quantity',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 5635), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 5635), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 21264), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 21264), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 5635), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 29, 59, 5635), editable=False),
        ),
    ]
