# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20170620_1534'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 317347), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 317347), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 348573), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 348573), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Technologies',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 332947), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 15, 36, 37, 332947), editable=False),
        ),
    ]
