# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20170621_1507'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dock', models.BooleanField(default=0)),
                ('Webcam', models.BooleanField(default=0)),
                ('Adopter', models.BooleanField(default=0)),
                ('SpikeGuard', models.BooleanField(default=0)),
                ('HeadPhones', models.BooleanField(default=0)),
                ('MagicJack', models.BooleanField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Dongle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNO', models.CharField(default=None, max_length=20)),
                ('Provider', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='KeyBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Tag', models.CharField(default=None, max_length=20)),
                ('Model', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Tag', models.CharField(default=None, max_length=20)),
                ('Sr_No', models.CharField(default=None, max_length=20)),
                ('Manufacturer', models.CharField(default=None, max_length=20)),
                ('Model', models.CharField(default=None, max_length=20)),
                ('Processor', models.CharField(default=None, max_length=20)),
                ('RAM', models.CharField(default=None, max_length=20)),
                ('OS', models.CharField(default=None, max_length=20)),
                ('Mem_Speed', models.CharField(default=None, max_length=20)),
                ('Purchased_Date', models.DateField(default=None, max_length=8)),
                ('Purchased_From', models.CharField(default=None, max_length=20)),
                ('Service_Date', models.DateField(default=None, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Device_Tag', models.CharField(default=None, max_length=20)),
                ('Model', models.CharField(default=None, max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 906401), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 906401), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 922002), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 922002), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 906401), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 17, 31, 31, 906401), editable=False),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TeamMembers'),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='accessories',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accessories'),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='dongle',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Dongle'),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='keyboard',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.KeyBoard'),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='laptop',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Laptop'),
        ),
        migrations.AddField(
            model_name='companyassets',
            name='mouse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Mouse'),
        ),
    ]
