# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 12:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20170626_1731'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignedAccessories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='Adopter',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='Dock',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='HeadPhones',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='MagicJack',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='SpikeGuard',
        ),
        migrations.RemoveField(
            model_name='accessories',
            name='Webcam',
        ),
        migrations.RemoveField(
            model_name='companyassets',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='companyassets',
            name='accessories',
        ),
        migrations.AddField(
            model_name='accessories',
            name='ID',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='accessories',
            name='count',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 799047), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 799047), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 814672), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 814672), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 799047), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 26, 18, 20, 36, 799047), editable=False),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Accessories_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Accessories'),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TeamMembers'),
        ),
    ]
