# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 05:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_auto_20170524_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Designations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DesignationName', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Designation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Designations'),
        ),
    ]
