# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20170606_1053'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='Group',
        ),
        migrations.AddField(
            model_name='teams',
            name='Group',
            field=models.ManyToManyField(to='main.CciGroups'),
        ),
    ]
