# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20170606_1303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teams',
            name='Group',
        ),
        migrations.AddField(
            model_name='teams',
            name='Group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CciGroups'),
        ),
    ]
