# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20170606_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='Address',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Date_of_joining_CCI',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Date_of_joining_Team',
            field=models.DateField(default=None, max_length=8),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Email',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Phone_No',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Qualification',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Skype_Id',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Technologies',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Year_of_passing',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
