# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20170606_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Email',
            field=models.EmailField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Skype_Id',
            field=models.EmailField(default=None, max_length=50),
        ),
    ]
