# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-06 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20170606_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Email',
            field=models.EmailField(default=None, error_messages={'required': 'this Email Id does not exist'}, max_length=50),
        ),
    ]
