# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 04:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_auto_20170606_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='DOB',
            field=models.DateField(default=None, max_length=8),
        ),
    ]
