# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_auto_20170607_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Phone_No',
            field=models.IntegerField(default=None, max_length=200),
        ),
    ]
