# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-07 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20170607_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammembers',
            name='Description',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
