# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-08 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20170608_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammembers',
            name='Pic',
            field=models.FileField(default='images/default.png', upload_to=''),
        ),
    ]
