# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_auto_20170609_1148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammembers',
            old_name='Billable_Status',
            new_name='BillableStatus',
        ),
        migrations.RenameField(
            model_name='teammembers',
            old_name='Employee_Status',
            new_name='EmployeeStatus',
        ),
    ]
