# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_auto_20170609_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billable_status',
            name='BillableStatus',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee_status',
            name='Status',
            field=models.CharField(max_length=20),
        ),
    ]
