# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20170609_1200'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='BillableStatus',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='EmployeeStatus',
        ),
        migrations.DeleteModel(
            name='Billable_Status',
        ),
        migrations.DeleteModel(
            name='Employee_Status',
        ),
    ]
