# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20170609_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billable_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillableStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
    ]
