# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_auto_20170609_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='Billablestatus',
        ),
        migrations.DeleteModel(
            name='Billable_Status',
        ),
    ]
