# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20170609_1257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='Employeestatus',
        ),
        migrations.DeleteModel(
            name='Employee_Status',
        ),
    ]
