# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-09 09:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_auto_20170609_1302'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billable_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BillableStatus', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Status', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='GroupName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Phone_No',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Year_of_passing',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], max_length=4, verbose_name='Year_of_passing'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='TeamLead',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='teams',
            name='TeamName',
            field=models.CharField(max_length=200),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Employeestatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Employee_Status'),
        ),
    ]
