# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20170609_1439'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ccigroups',
            old_name='GroupName',
            new_name='Name',
        ),
        migrations.AddField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=None),
        ),
        migrations.AddField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=None),
        ),
    ]
