# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 10:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0041_auto_20170619_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccigroups',
            name='Name',
        ),
        migrations.AddField(
            model_name='ccigroups',
            name='GroupName',
            field=models.CharField(default=None, max_length=200, verbose_name='Name'),
        ),
    ]
