# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0045_auto_20170619_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 17, 39, 36, 254843)),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 17, 39, 36, 254843)),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='Name',
            field=models.CharField(db_column='GroupName', default=None, max_length=200),
        ),
    ]
