# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0052_auto_20170619_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ccigroups',
            name='DateCreated',
        ),
        migrations.RemoveField(
            model_name='ccigroups',
            name='DateModified',
        ),
    ]
