# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 12:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0053_auto_20170619_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 17, 54, 53, 407510)),
        ),
        migrations.AddField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 19, 17, 54, 53, 407510)),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='GroupName',
            field=models.CharField(db_column='Name', default=None, max_length=200),
        ),
    ]
