# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 05:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0055_auto_20170620_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 2, 37, 34447), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 2, 37, 34447), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 2, 37, 49487), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 2, 37, 49487), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='TeamLead',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='teams',
            name='Tech',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
