# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 06:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0056_auto_20170620_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 45, 52, 998703), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 45, 52, 998703), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(db_column='BillableStatus', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Date_of_joining_CCI',
            field=models.DateField(db_column='YearofJoiningCCI', default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Date_of_joining_Team',
            field=models.DateField(db_column='YearofJoiningTeam', default=None, max_length=8),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Description',
            field=models.CharField(db_column='BriefDescription', default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Email',
            field=models.EmailField(db_column='EmailId', default=None, error_messages={'required': 'this Email Id does not exist'}, max_length=50),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Employeestatus',
            field=models.ForeignKey(db_column='MemberStatus', default=1, on_delete=django.db.models.deletion.CASCADE, to='main.Employee_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Phone_No',
            field=models.IntegerField(db_column='phoneNumber'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Pic',
            field=models.FileField(db_column='Image', default='Images/default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Qualification',
            field=models.CharField(db_column='HighestQualification', default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Skype_Id',
            field=models.EmailField(db_column='SkypeId', default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Team',
            field=models.ForeignKey(db_column='TeamId', default=1, on_delete=django.db.models.deletion.PROTECT, to='main.Teams'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Year_of_passing',
            field=models.IntegerField(choices=[(1980, 1980), (1981, 1981), (1982, 1982), (1983, 1983), (1984, 1984), (1985, 1985), (1986, 1986), (1987, 1987), (1988, 1988), (1989, 1989), (1990, 1990), (1991, 1991), (1992, 1992), (1993, 1993), (1994, 1994), (1995, 1995), (1996, 1996), (1997, 1997), (1998, 1998), (1999, 1999), (2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017)], db_column='YearOfPassing', max_length=4, verbose_name='Year_of_passing'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 45, 53, 12741), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 11, 45, 53, 12741), editable=False),
        ),
    ]
