# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 07:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0066_auto_20170620_1306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 14, 34, 83269), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 14, 34, 83269), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 14, 34, 83269), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 13, 14, 34, 83269), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='TeamName',
            field=models.CharField(db_column='Name', max_length=200),
        ),
    ]
