# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-20 10:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0067_auto_20170620_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='Billablestatus',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='Employeestatus',
        ),
        migrations.AddField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 67396), editable=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 67396), editable=False),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Desigtn',
            field=models.CharField(db_column='Designation', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='Gmail',
            field=models.EmailField(db_column='GmailId', default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='IsTeanLead',
            field=models.BooleanField(db_column='IsTeanLead', default=0),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 51770), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 51770), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Designation',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Designations'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Phone_No',
            field=models.CharField(db_column='phoneNumber', max_length=10),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 51770), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 20, 16, 1, 48, 51770), editable=False),
        ),
    ]
