# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-21 06:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0070_auto_20170620_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='BillStatus',
        ),
        migrations.RemoveField(
            model_name='teammembers',
            name='MemStatus',
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 274352), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 274352), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Billablestatus',
            field=models.ForeignKey(db_column='BillableStatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Billable_Status'),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 289979), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 289979), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='Employeestatus',
            field=models.ForeignKey(db_column='EmployeeStatus', default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.Employee_Status'),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 274352), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 21, 12, 0, 11, 274352), editable=False),
        ),
    ]
