# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0073_auto_20170626_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAssignedCompanyAssets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity', models.CharField(default=None, max_length=20)),
                ('CompanyAssets_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.CompanyAssets')),
            ],
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 599108), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 599108), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 614758), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 614758), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 599108), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 14, 53, 17, 599108), editable=False),
        ),
        migrations.AddField(
            model_name='userassignedcompanyassets',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TeamMembers'),
        ),
    ]
