# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0074_auto_20170627_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userassignedcompanyassets',
            name='CompanyAssets_Id',
        ),
        migrations.RemoveField(
            model_name='userassignedcompanyassets',
            name='Name',
        ),
        migrations.RemoveField(
            model_name='userassignedaccessories',
            name='Accessories_Id',
        ),
        migrations.AddField(
            model_name='companyassets',
            name='Name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.TeamMembers'),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Adopter',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Dock',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='HeadPhone',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='SpikeGuard',
            field=models.BooleanField(default=0),
        ),
        migrations.AddField(
            model_name='userassignedaccessories',
            name='Webcam',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 231494), editable=False),
        ),
        migrations.AlterField(
            model_name='ccigroups',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 231494), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 247123), editable=False),
        ),
        migrations.AlterField(
            model_name='teammembers',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 247123), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateCreated',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 231494), editable=False),
        ),
        migrations.AlterField(
            model_name='teams',
            name='DateModified',
            field=models.DateTimeField(default=datetime.datetime(2017, 6, 27, 15, 20, 48, 231494), editable=False),
        ),
        migrations.DeleteModel(
            name='Accessories',
        ),
        migrations.DeleteModel(
            name='UserAssignedCompanyAssets',
        ),
    ]
